@startuml
title Android Oplus Settings DeviceInfo

DeviceInfoFragment ++
DeviceInfoFragment --> MyDeviceInfoFragment ++: super.onAttach()
MyDeviceInfoFragment -> DashboardFragment ++: super.onAttach()
MyDeviceInfoFragment --

DashboardFragment -> DashboardFragment ++: createPreferenceControllers()
DashboardFragment -> DeviceInfoFragment ++: createPreferenceControllers()
DeviceInfoFragment -> DeviceInfoFragment ++: buildPreferenceControllers()
DeviceInfoFragment --> DashboardFragment --: List<AbstractPreferenceController>
DeviceInfoFragment --
DashboardFragment --

DashboardFragment -> PreferenceControllerListHelper ++: getPreferenceControllersFromXml()
  note over PreferenceControllerListHelper: get METADATA_CONTROLLER and METADATA_KEY from xml
  PreferenceControllerListHelper -> BasePreferenceController ++: createInstance()
  BasePreferenceController --> PreferenceControllerListHelper --
PreferenceControllerListHelper --> DashboardFragment --: List<AbstractPreferenceController>

DashboardFragment -> PreferenceControllerListHelper ++: filterControllers()
PreferenceControllerListHelper --> DashboardFragment --: List<AbstractPreferenceController>

DashboardFragment --
DeviceInfoFragment --


DeviceInfoFragment -> DeviceInfoFragment ++: onCreate()
DeviceInfoFragment -> MyDeviceInfoFragment ++: super.onCreate()
MyDeviceInfoFragment -> DashboardFragment ++: super.onCreate()
MyDeviceInfoFragment --

note over DashboardFragment: DashboardFragment is PreferenceFragmentCompat\nonCreate() calls onCreatePreference()
DashboardFragment -> DashboardFragment ++: onCreatePreferences()
DashboardFragment -> DashboardFragment ++: refreshAllPreferences()
DashboardFragment -> DashboardFragment ++: displayResourceTiles()
DashboardFragment -> DeviceInfoFragment ++: getPreferenceScreenResId()
DeviceInfoFragment --> DashboardFragment --: R.xml.device_info

DashboardFragment --
DashboardFragment -> DashboardFragment ++: refreshDashboardTiles()
DashboardFragment --
DashboardFragment --
DashboardFragment --

DashboardFragment -> DashboardFragment ++: onCreate()
DashboardFragment -> DashboardFragment ++: updatePreferenceStates()
DashboardFragment --
DashboardFragment --
DashboardFragment --

@enduml